config/routes.rb
Rails.application.routes.draw do
  get 'principal_page/index'
  get 'pokemon_with_rails/index'
  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => 'principal_page#index'
end

app/models/api.rb
class Api < ApplicationRecord
  attr_reader :uri

  def initialize(uri)
    @uri = uri
  end

  def PokemoAll
    begin
      datos = RestClient.get "#{uri}?offset=1000&limit=1000", { 'Content-Type': 'application/json', 'Accept': 'application/json' }
      return datos
    rescue RestClient::ExceptionWithResponse => e
      return JSON.parse(e.response).to_json
    rescue => e
      return (44).to_json
    end
  end

  def PokemoSearch(pokemon)
    begin
      datos = RestClient.get "#{uri}#{pokemon}", { 'Content-Type': 'application/json', 'Accept': 'application/json' }
      return datos
    rescue RestClient::ExceptionWithResponse => e
      return JSON.parse(e.response).to_json
    rescue => e
      return (44).to_json
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pokemon_with_rails_controller.rb
class PokemonWithRailsController < ApplicationController
  def index
    @uri = "https://pokeapi.co/api/v2/pokemon/"
    api = Api.new(@uri)
    if params[:search].present?
      @dtos = api.PokemoSearch(params[:search])
      result = JSON.parse @dtos.to_str
      @pokemons = Kaminari.paginate_array(result['results']).page(params[:page]).per(12)
      if @pokemons.empty?
        @error = 1
      end
    else
      @dtos = api.PokemoAll
      result = JSON.parse @dtos.to_str
      @pokemons = Kaminari.paginate_array(result['results']).page(params[:page]).per(12)
    end

  end
end

app/controllers/principal_page_controller.rb
class PrincipalPageController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pokemon_with_rails_helper.rb
module PokemonWithRailsHelper
end

app/helpers/principal_page_helper.rb
module PrincipalPageHelper
end

app/views/home/index.html.erb
<div class="row" style="margin-left: 10px">
  <div class="col-md-12">
    <div class="ibox float-e-margins">
      <div class="ibox-title"><h1>Pokemons</h1>
        <br><br>

        <div class="ibox-content">
          <%= link_to '<i class="fa fa-chevron-left"></i> '.html_safe + 'Volver', principal_page_index_path, class: 'btn btn-xs btn-warning' %>
          <br><br>
          <div class="row" id="padre">
          </div>

          <div style="text-align: center; margin-top: 20px;">
            <button id="prevPage">Anterior</button>
            <span id="currentPage">1</span>/<span id="totalPages">1</span>
            <button id="nextPage">Siguiente</button>
          </div>
        </div>


      </div>
      <br>
      <%= link_to '<i class="fa fa-chevron-left"></i> '.html_safe + 'Volver', principal_page_index_path, class: 'btn btn-xs btn-warning' %>

    </div>
  </div>
</div>

<script type="text/javascript" charset="utf-8">
    home();
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pokemon</title>

  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= csrf_meta_tags %>
  <%= Gon::Base.render_data %>

</head>

<body>
<%= yield %>
<div class="col-md-12" align="center">
  <div id="copyright">Copyright&copy; <%= Time.now.strftime("%Y") %> - Página creada por José Domingo Santillán
    Rodríguez - Todos los derechos reservados
  </div>
</div>
</body>
</html>

app/views/pokemon_with_rails/_dynamic.html.erb
<%= stylesheet_link_tag 'pokemon_with_rails' %>
<div class="row">
  <div class="col-md-12 offset-md-5 text-right" style="margin-bottom: 2em;">
    <div class="pag_right" id="pag1"><%= page_entries_info @pokemons, entry_name: @pokemons.length == 1 ? 'Pokemon' : 'Pokemon'.pluralize %></div>
    <div class="detall_left"><%= paginate @pokemons, params: { controller: 'pokemon_with_rails', action: 'index' }, :theme => 'twitter-bootstrap-3', :pagination_class => 'pagination-sm', remote: true %></div>
  </div>
</div>
<% @pokemons.each do |pokemon| %>
  <% imagen = Api.new(@uri).PokemoSearch(pokemon['name']) %>
  <% result = JSON.parse imagen.to_str %>
  <% imagen_mostar = result['sprites']['front_default'] %>
  <div class="col-md-3">
    <div class="card">
      <img class="card-img-top" src="<%= imagen_mostar %>" alt="img_<%= pokemon['name'] %>" style=" width: 100px; height: 100px;margin: auto;display: block">
      <div class="card-body">
        <h5 class="card-title" style="text-align: center"><%= pokemon['name'] %>
          <span><%= result['stats'][0]['base_stat'] %>hp</span></h5>
        <p class="card-body-text">Exp <%= result['base_experience'] %></p>
      </div>
      <div class="card-footer">
        <div class="card-footer-social">
          <h3><%= result['stats'][1]['base_stat'] %></h3>
          <p><i class="fa fa-rocket" aria-hidden="true"></i> Ataque</p>
        </div>
        <div class="card-footer-social">
          <h3><%= result['stats'][2]['base_stat'] %></h3>
          <p><i class="fa fa-star" aria-hidden="true"></i> Especial</p>
        </div>
        <div class="card-footer-social">
          <h3><%= result['stats'][3]['base_stat'] %></h3>
          <p><i class="fa fa-shield" aria-hidden="true"></i> Defensa</p>
        </div>
      </div>
    </div>
  </div>
<% end %>
<div class="row">
  <div class="col-md-12 offset-md-5 text-right" style="margin-bottom: 2em;">
    <div class="detall_left"><%= paginate @pokemons, params: { controller: 'pokemon_with_rails', action: 'index' }, :theme => 'twitter-bootstrap-3', :pagination_class => 'pagination-sm', remote: true %></div>
    <div class="pag_right" id="pag1"><%= page_entries_info @pokemons, entry_name: @pokemons.length == 1 ? 'Pokemon' : 'Pokemon'.pluralize %></div>
  </div>
</div>

app/views/pokemon_with_rails/index.html.erb
<%= stylesheet_link_tag 'pokemon_with_rails' %>
<div class="row" style="margin-left: 10px">
  <div class="col-md-12">
    <div class="ibox float-e-margins">
      <div class="ibox-title"><h1>Pokemons</h1>
        <br><br>
        <%= link_to '<i class="fa fa-chevron-left"></i> '.html_safe + 'Volver', principal_page_index_path, class: 'btn btn-xs btn-warning' %>
        <div class="ibox-content">
          <br><br>
          <div class="fixed-table-loading table table-hover table-striped table-sm" id="div_cargando" style="display:none"></div>
          <div class="row" id="vista" style="margin-right: 10px">
            <%= render :partial => 'dynamic' %>
          </div>
        </div>
        <%= link_to '<i class="fa fa-chevron-left"></i> '.html_safe + 'Volver', principal_page_index_path, class: 'btn btn-xs btn-warning' %>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript" charset="utf-8">
    pokemon_with_rails();
</script>

app/views/pokemon_with_rails/index.js.erb
$("#vista").html("<%= escape_javascript(render("dynamic")) %>");

ocultar_div_y_mostrar_table('vista', 'div_cargando');

app/views/principal_page/index.html.erb
<%= stylesheet_link_tag 'principal_page' %>
<div class="row" style="margin-left: 10px">
  <div class="col-md-12">
    <div class="ibox float-e-margins" style="margin-right: 20px">
      <div class="ibox-title" style="text-align: center; background-color: #730E15; color: white; margin-top: 10px; height: 130px; border-radius: 30px">
        <br>
        <h1>Pokemon Api <i class="fa fa-database"></i></h1>
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <div class="ibox float-e-margins" style="margin-right: 20px">
      <div class="ibox-title" style="text-align: center; background-color: #003057; color: white; margin-top: 10px; height: 410px; border-radius: 30px">
        <br>
        <h1>Javascript.</h1>
        <br>
        <h3>En esta versión se podrá visualizar el consumno de la API de Pokemon, utilizando Javascript <i class="fa fa-laptop"></i></h3>
        <br>
        <%= link_to home_index_path, class: 'btn btn_back' do %>
          Ir <i class="fa fa-share"></i>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <div class="ibox float-e-margins" style="margin-right: 20px">
      <div class="ibox-title" style="text-align: center; background-color: #edff21; color: white; margin-top: 10px; height: 410px; border-radius: 30px">
        <br>
        <h1>Ruby on Rails.</h1>
        <br>
        <h3>En esta versión se podrá visualizar el consumno de la API de Pokemon, utilizando Ruby on Rails <i class="fa fa-laptop"></i></h3>
        <br>
        <%= link_to pokemon_with_rails_index_path, class: 'btn btn_back' do %>
          Ir <i class="fa fa-share"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>